from .civilian import Civilian as Civilian
from .guard import Guard as Guard
from .hunter import Hunter as Hunter
from .idiot import Idiot as Idiot
from .joker import Joker as Joker
from .player import Player as Player
from .prophet import Prophet as Prophet
from .werewolf import Werewolf as Werewolf
from .witch import Witch as Witch
from .wolfking import WolfKing as WolfKing
