name: Lint

on:
  push:
    paths:
      - "nonebot_plugin_werewolf/**"
      - ".github/workflows/lint.yml"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Ruff Lint
        uses: astral-sh/ruff-action@v2
        with:
          src: >-
            nonebot_plugin_werewolf/

  basedpyright:
    name: BasedPyright Lint (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    needs: ruff
    concurrency:
      group: bp-${{ github.ref }}-${{ matrix.python-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --python ${{ matrix.python-version }}

      - name: Run BasedPyright
        run: uv tool run basedpyright nonebot_plugin_werewolf/ --pythonpath ./.venv/bin/python
