name: Publish

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # For private repository
      contents: read
      # For PyPI trusted publishing
      id-token: write

    steps:
      - uses: actions/checkout@master

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.12"
          cache: true

      - name: Build dist
        run: pdm build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
