name: Publish

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # For private repository
      contents: read
      # For PyPI trusted publishing
      id-token: write

    steps:
      - uses: actions/checkout@master

      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Build dist
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
