name: Pyright Lint

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "nonebot_plugin_werewolf/**"
      - ".github/workflows/pyright.yml"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  pyright:
    name: Pyright Lint (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    concurrency:
      group: pyright-${{ github.ref }}-${{ matrix.python-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv python install ${{ matrix.python-version }}
          uv sync --python ${{ matrix.python-version }}

      - name: Configure venv
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
